### ISSUE TITLE
Congiruring router

### ISSUE THREAD

**Issue by catalinux** [ghua/DirectBundle#3]
Hi, 

I do not get where should I put the following code

```
  ext_direct:
        basic:
          error_template: ExtDirectBundle::extjs_errors.html.twig
    router:
        rules:
            getCustomers:
                defaults: { _controller: AcmeDemoBundle:Demo:getCustomers, params: true }
                reader: { root: root }

            getCountries:
                defaults: { _controller: AcmeDemoBundle:Demo:getCountries }

            getRoles:
                defaults: { _controller: AcmeDemoBundle:Demo:getRoles }

            updateCustomer:
                defaults: { _controller: AcmeDemoBundle:Demo:updateCustomer, params: true }

            createCustomer:
                defaults: { _controller: AcmeDemoBundle:Demo:createCustomer, params: true, form: true }

            chat:
                defaults: { _controller: chat_service:chat, params: true, form: true }
```
